# Generated by Django 6.0.7 on 2026-07-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('prism_id', models.CharField(max_length=50, unique=True, verbose_name='PRISM ID')),
                ('category', models.CharField(choices=[('central', 'Central'), ('state', 'State')], default='state', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
