# Generated by Django 6.0.7 on 2026-07-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_district_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='districts',
            field=models.ManyToManyField(blank=True, related_name='officers', to='accounts.district'),
        ),
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='leaders', to='accounts.project'),
        ),
    ]
