# Generated by Django 6.0.7 on 2026-07-23 01:02
# Hand-edited: add the FKs and copy existing M2M assignments across BEFORE
# dropping the old join tables, so no assignment is lost.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def m2m_to_fk(apps, schema_editor):
    """Copy each project's/district's first assignee into the new single FK."""
    Project = apps.get_model('accounts', 'Project')
    District = apps.get_model('accounts', 'District')
    for p in Project.objects.all():
        u = p.leaders.first()  # M2M reverse accessor, still present here
        if u:
            p.leader = u
            p.save(update_fields=['leader'])
    for d in District.objects.all():
        u = d.officers.first()
        if u:
            d.officer = u
            d.save(update_fields=['officer'])


def fk_to_m2m(apps, schema_editor):
    """Reverse: rebuild the M2M links from the FKs."""
    Project = apps.get_model('accounts', 'Project')
    District = apps.get_model('accounts', 'District')
    for p in Project.objects.all():
        if p.leader_id:
            p.leaders.add(p.leader)
    for d in District.objects.all():
        if d.officer_id:
            d.officers.add(d.officer)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_districts_user_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='districts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(m2m_to_fk, fk_to_m2m),
        migrations.RemoveField(
            model_name='user',
            name='districts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='projects',
        ),
    ]
