# Generated by Django 6.0.7 on 2026-07-24 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_districts_remove_user_projects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='targeted_user',
            field=models.CharField(blank=True, help_text='Who the project serves, e.g. Citizens, Dept. officials.', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='accounts.department'),
        ),
        migrations.CreateModel(
            name='MPRPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('due_date', models.DateField()),
                ('is_open', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='unique_mpr_period')],
            },
        ),
        migrations.CreateModel(
            name='MPREntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('event', 'Major events planned'), ('review', "Review by Hon'ble Minister / Others"), ('training', 'Major training'), ('award', 'Major awards'), ('significant', 'Significant activities planned'), ('new_activity', 'New activities planned'), ('enhancement', 'Major enhancements')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('participants', models.PositiveIntegerField(blank=True, null=True)),
                ('target_user', models.CharField(blank=True, max_length=200)),
                ('suggestions', models.TextField(blank=True)),
                ('event_category', models.CharField(blank=True, choices=[('inauguration', 'Inauguration'), ('launch', 'Launch'), ('press', 'Press coverage'), ('other', 'Others')], max_length=20)),
                ('award_level', models.CharField(blank=True, choices=[('international', 'International'), ('national', 'National'), ('state', 'State'), ('district', 'District'), ('local', 'Local')], max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='mpr/awards/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpr_entries', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpr_entries', to='accounts.project')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounts.mprperiod')),
            ],
            options={
                'verbose_name_plural': 'MPR entries',
                'ordering': ['kind', 'date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='accounts.project')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_month', models.CharField(blank=True, max_length=100)),
                ('reporting_month', models.CharField(blank=True, max_length=100)),
                ('cumulative', models.CharField(blank=True, max_length=100, verbose_name='Cumulative since inception')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='accounts.mprperiod')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='accounts.projectparameter')),
            ],
            options={
                'ordering': ['parameter'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectparameter',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_project_parameter'),
        ),
        migrations.AddConstraint(
            model_name='parametervalue',
            constraint=models.UniqueConstraint(fields=('period', 'parameter'), name='unique_parameter_value'),
        ),
    ]
