# Generated by Django 6.0.7 on 2026-07-24 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_department_project_targeted_user_project_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPRLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('unlock_requested', models.BooleanField(default=False)),
                ('unlock_reason', models.TextField(blank=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='accounts.mprperiod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpr_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-locked_at'],
                'constraints': [models.UniqueConstraint(fields=('period', 'user'), name='unique_mpr_lock')],
            },
        ),
    ]
