# Generated by Django 6.0.7 on 2026-07-26 18:36

from django.db import migrations, models


def backfill_scope(apps, schema_editor):
    """Rows predate the split: everything a DIO-only author filed is a district report."""
    apps.get_model("accounts", "MPREntry").objects.filter(
        author__is_dio=True, author__is_pl=False).update(scope="district")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_mprlock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mprentry',
            options={'ordering': ['scope', 'kind', 'date', 'id'], 'verbose_name_plural': 'MPR entries'},
        ),
        migrations.AddField(
            model_name='mprentry',
            name='scope',
            field=models.CharField(choices=[('district', 'District report'), ('project', 'Project report')], default='project', max_length=10),
        ),
        migrations.RunPython(backfill_scope, migrations.RunPython.noop),
    ]
