# Generated by Django 6.0.7 on 2026-07-28 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_designation_placeofposting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mprentry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mpr_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mprentry',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounts.mprperiod'),
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='accounts.projectparameter'),
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parameter_values', to='accounts.mprperiod'),
        ),
        migrations.AlterField(
            model_name='projectparameter',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parameters', to='accounts.project'),
        ),
    ]
