# Generated by Django 6.0.7 on 2026-07-29 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_mprentry_author_alter_mprentry_period_and_more'),
    ]

    operations = [
    ]
