# Generated by Django 6.0.7 on 2026-07-30 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_gl',
            field=models.BooleanField(default=False, verbose_name='Group Leader'),
        ),
        migrations.AlterField(
            model_name='district',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='districts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='accounts.projectparameter'),
        ),
    ]
