# Generated by Django 6.0.7 on 2026-08-03 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_is_gl_alter_district_officer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='districts', to=settings.AUTH_USER_MODEL),
        ),
    ]
