# Generated by Django 6.0.7 on 2026-08-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_project_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='prism_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='PRISM ID'),
        ),
    ]
