# Generated by Django 6.0.7 on 2026-08-06 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_project_prism_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mprentry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mpr_entries', to='accounts.project'),
        ),
    ]
