# Generated by Django 6.0.7 on 2026-09-18 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_mprentry_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('login_ok', 'Signed in'), ('login_fail', 'Sign-in failed'), ('logout', 'Signed out'), ('locked_out', 'Locked out'), ('lock_cleared', 'Lock cleared'), ('password_changed', 'Password changed'), ('role_changed', 'Roles changed'), ('user_created', 'User created'), ('user_disabled', 'User disabled'), ('user_enabled', 'User re-enabled'), ('user_deleted', 'User deleted')], max_length=20)),
                ('actor_label', models.CharField(max_length=150)),
                ('target_label', models.CharField(blank=True, max_length=150)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('detail', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events_about', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['-at'], name='accounts_se_at_c83949_idx'), models.Index(fields=['actor_label'], name='accounts_se_actor_l_c3e78a_idx')],
            },
        ),
    ]
